### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by hawkins** [patrickdmiller/streamdeck-kef#1]
Hey, great work on this! You mentioned some windows testing was done, is there a branch somewhere for building/running on windows? Out of the box it doesn't seem to work for me, so I thought I'd check with you before I dive too deep into figuring out what's going on in case I might just be duplicating your work. Thanks!

**Comment by patrickdmiller** [comment]
Hi Josh, Thanks! I can try and compile for windows tonight. I don't use
Windows much but will see if it works :D I think I tried it once a year or
so ago.
